name: Print world

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World from GitHub Actions"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome message
        run: echo "Welcome to GitHub Actions"
