name: Print world

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World from GitHub Actions"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome message
        run: echo "Welcome to GitHub Actions"
